### ISSUE TITLE
Use Binding to manage color values

### ISSUE THREAD

**Issue by Peter-Schorn** [jordanbaird/ColorWell#5]
Instead of accepting two parameters in the `ColorWellView` initializer, `color`, and `action`, you could use a single `Binding` parameter. This is cleaner and what the rest of the SwiftUI interface uses.

**Comment by jordanbaird** [comment]
This is in the process of happening. I've actually been reworking a lot of the API for both the Cocoa and SwiftUI views. I may end up archiving this repo and starting fresh once I get it in a state that I'm happy with.

**Comment by Peter-Schorn** [comment]
You also have way more initializers than you need. Just make the parameters optional and/or add default values and you get the same interface for much less code.

**Comment by jordanbaird** [comment]
The new repository is now available at https://github.com/jordanbaird/ColorWellKit, with a number of changes to the SwiftUI interface to more closely align with SwiftUI's conventions. Closing this now, but if there are still problems, feel free to open a new issue there.
