### ISSUE TITLE
Colorwell does not work on macOS Sonoma

### ISSUE THREAD

**Issue by jameszjwchang** [jordanbaird/ColorWell#7]
Hello!

When I tried to use this package, it resulted in the color picker covering up the entire view; there was also no way to adjust the size of the picker and the picker itself does not seem to work. Is there a reason for why this is happening?

<img width="562" alt="Screenshot 2023-07-04 at 21 02 07" src="https://github.com/jordanbaird/ColorWell/assets/120231221/51df168e-2f43-4cc0-9dfa-5745e5e3eae8">

**Comment by jordanbaird** [comment]
Interesting. I don't have a Mac with Sonoma on it right now, so I can't test this. Can you share the exact code that produces the problem?

**Comment by jameszjwchang** [comment]
Hello, sorry for replying late; I don't have the code anymore, but I believe that the issue had to do with embedding the color well inside a form with the GroupedForm style enabled. Perhaps some debugging while implementing the color well inside complex view elements (such as forms, lists) would help.

**Comment by milanvarady** [comment]
Hi, I'm experiencing the same exact issue. The color picker takes up the entire view, regardless of the specified `colorWellStyle`, when on Sonoma. I was able to reproduce this with a very minimal project, just a fresh project with the `ColorWellView` in a `VStack`. Here is the code I used:

```swift
import SwiftUI
import ColorWell

struct ContentView: View {
    @Binding var fontColor: Color
    
    var body: some View {
        VStack {
            ColorWellView(color: fontColor)
                .colorWellStyle(.expanded)
        }
    }
}

#Preview {
    @State var color: Color = .white
    
    return ContentView(fontColor: $color)
}
```

**Comment by jordanbaird** [comment]
Sorry I've been sitting on this issue for so long. I've actually had plans to replace this repository with a new one, as the current API has a lot of issues. It's available now at https://github.com/jordanbaird/ColorWellKit, and this issue should be fixed. I'll close this, but if you find that you're still having problems with the new repo, feel free to open a new issue there.
